name: Laravel Deployment

on:
  push:
    branches:
      - 10.x

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."
        
      - name: Deploy to Ubuntu VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/laravel
            git config --global --add safe.directory /var/www/html/laravel
            git fetch origin 10.x
            # Check for merge conflicts
            if git merge-base --is-ancestor origin/10.x HEAD; then
              git pull origin 10.x
              php artisan migrate
            else
              echo "Merge conflicts detected. Please resolve conflicts manually."
              # You can add additional actions here to notify or handle the conflicts
              exit 1
            fi

